engines/OnDeck/config/routes.rb
OnDeck::Engine.routes.draw do

  root :to => 'home#index'

  get 'api/recommendations' => 'api#recommendations', defaults: { format: 'json' }
end

engines/OnDeck/app/models/on_deck/application_record.rb
module OnDeck
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/OnDeck/app/models/on_deck/event_global_dominance_score.rb
module OnDeck
  class EventGlobalDominanceScore < ApplicationRecord
  end
end

engines/OnDeck/app/models/on_deck/event_past_performance_score.rb
module OnDeck
  class EventPastPerformanceScore < ApplicationRecord
  end
end

engines/OnDeck/app/models/on_deck/upcoming_recommendation.rb
module OnDeck
  class UpcomingRecommendation < ApplicationRecord
  end
end

engines/OnDeck/app/controllers/on_deck/api_controller.rb
require_dependency "on_deck/application_controller"

module OnDeck
  class ApiController < ApplicationController

    def recommendations
      respond_with(UpcomingRecommendation.all.map { |x| JSON.parse(x.data) })
    end

  end
end

engines/OnDeck/app/controllers/on_deck/application_controller.rb
module OnDeck
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    respond_to :json, :xml
  end
end

engines/OnDeck/app/controllers/on_deck/home_controller.rb
require_dependency "on_deck/application_controller"

module OnDeck
  class HomeController < ApplicationController
  end
end

engines/OnDeck/app/helpers/on_deck/admin_helper.rb
module OnDeck
  module AdminHelper
  end
end

engines/OnDeck/app/helpers/on_deck/application_helper.rb
module OnDeck
  module ApplicationHelper
  end
end

engines/OnDeck/app/views/layouts/on_deck/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FRC On Deck</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "on_deck/application", media: "all" %>
  <%= javascript_include_tag "on_deck/application" %>
</head>
<body>

<%= yield %>

</body>
</html>

engines/OnDeck/app/views/on_deck/home/index.html.erb
<%= react_component 'FRCOnDeck', rec_url: api_recommendations_path %>